---
# tasks file for conditions
- name: print a message
  debug:
    msg: "Hi! This is start of condition testing"

- name: install apache 2
  apt:
    name: apache2
    state: present
  when: apache2_install_flag

- name: get os family
  debug:
    var: ansible_facts['os_family']
- name: get distribution major version
  debug:
    var: ansible_facts['distribution_major_version']
- name: show kernel version with condition
  debug:
    var: ansible_facts['kernel_version']
  when:
    - ansible_facts['os_family'] == "Debian"
    - ansible_facts['distribution_major_version'] > "20"

- name: setting complex condition
  debug:
    var: ansible_facts['kernel_version']
  when: ansible_facts['os_family'] == "Debian" and ansible_facts['distribution_major_version'] | int >= 20

# check file content
- name: create a file
  ansible.builtin.copy:
    dest: /tmp/file1.txt
    content: "Hi"
- name: register a variable
  ansible.builtin.command: cat /tmp/file1.txt 
  register: file_content
- name: use the variabel in conditional statement
  debug:
    var: file_content
- name: use the variabel in conditional statement
  debug:
    msg: "{{file_content.stdout}}" 
  when: file_content.stdout.find('Hi') != -1

# loop
- name: print loop
  ansible.builtin.command: echo {{ item }}    
  loop: [0,3,2,6,2,8,1,9]
  when: item > 5

- name: how to print ansible ansible_facts
  debug:
    var: ansible_facts['distribution']
    # var: ansible_facts['distribution_major_version']
    # var: ansible_facts['kernel_version']
    # var: ansible_facts
  when: ansible_facts['os_family'] == "Debian"

