---
# tasks file for custom-module
- name: Create a file using custom module - from library
  file_present:
    path: /tmp/demo.txt
    content: "Hello from custom module"
    state: present

- name: Test collection module
  myorg.filetools.file_present:
    path: /tmp/collection_ok.txt
    content: "Collection works!"
    state: present