---
- name: print string value
  debug:
    msg: "Hello"
- name: print variabel value measure
  debug:
    var: measure
- name: print varaiable value using brackets
  debug:
    msg: "{{ measure }}"
- name: print varaibel values from vars_files
  debug:
    msg: "{{ uname }} {{ qual }}"
- name: print lsit
  debug:
    var: fruits
- name: print one item from fruies list
  debug:
    msg: "{{ fruits[0] }}"
- name: print map
  debug:
    msg: "{{ prices }}"
- name: print one item from map
  debug:
    msg: "{{ prices.apple }} {{ prices['mango'] }}"
- name: pass variable value from command line
  debug:
    msg: "{{measure}} {{website}}"
- name: pass variable - pass variable file name as input
  debug:
    msg: "{{ uname }} {{ qual}}" 

- name: print value of env variable
  ansible.builtin.shell: "echo $EXAMPLE"

- name: print env var value using debug - var
  debug:
    var: ansible_env.EXAMPLE
- name: print env var value using debug - msg
  debug:
    msg: "{{ansible_env.EXAMPLE}}"

- name: save env var value in a new variable - 'result'
  ansible.builtin.shell: "echo $EXAMPLE"
  register: result
- name: print value of 'result' variable
  debug:
    msg: "{{result.stdout}}"
